CREATE TABLE IF NOT EXISTS T_ORDER
(
    ID                 BIGSERIAL PRIMARY KEY,
    USER_ID            BIGINT       NOT NULL,
    STATUS             VARCHAR(255) NOT NULL,
    ORDER_DETAIL       TEXT,
    TOTAL_AMOUNT       NUMERIC(19, 4),
    CREATED_BY         VARCHAR(255),
    CREATED_DATE       TIMESTAMP(6),
    LAST_MODIFIED_BY   VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS ORDER_STATUS_HISTORY
(
    ID                 BIGSERIAL PRIMARY KEY,
    ORDER_ID           BIGINT       NOT NULL,
    STATUS             VARCHAR(255) NOT NULL,
    ORDER_DETAIL       TEXT,
    CREATED_BY         VARCHAR(255),
    CREATED_DATE       TIMESTAMP(6),
    LAST_MODIFIED_BY   VARCHAR(255),
    LAST_MODIFIED_DATE TIMESTAMP(6)
);
